export const ActionTypes ={
  FETCH_NEWS: "FETCH_NEWS",
    GET_NEWS : "GET_NEWS",
    BOOKMARK_ITEM:"BOOKMARK_ITEM",
  UNBOOKMARK_ITEM: "UNBOOKMARK_ITEM",
  GET_BOOKMARK_ITEMS: " GET_BOOKMARK_ITEMS",
}